/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Fabián
 */
public class Menu extends javax.swing.JFrame {

    
    public Menu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuCerrarSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        VentanaVehiculos = new javax.swing.JMenuItem();
        VentaCarrito = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        VentanaCompras = new javax.swing.JMenuItem();
        VentanaEditar = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VentanaPrincipal.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout VentanaPrincipalLayout = new javax.swing.GroupLayout(VentanaPrincipal);
        VentanaPrincipal.setLayout(VentanaPrincipalLayout);
        VentanaPrincipalLayout.setHorizontalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        VentanaPrincipalLayout.setVerticalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar-sesion.png"))); // NOI18N
        jMenu1.setText("Salir de la sesion");

        MenuCerrarSesion.setText("Cerrar sesion");
        MenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCerrarSesion);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/coche.png"))); // NOI18N
        jMenu2.setText("Visualizar vehiculos");

        VentanaVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/coche.png"))); // NOI18N
        VentanaVehiculos.setText("Ver vehiculos");
        VentanaVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaVehiculosActionPerformed(evt);
            }
        });
        jMenu2.add(VentanaVehiculos);

        jMenuBar1.add(jMenu2);

        VentaCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/carrito-de-compras.png"))); // NOI18N
        VentaCarrito.setText("Compras");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/carrito-de-compras (1).png"))); // NOI18N
        jMenuItem4.setText("Ver compras realizadas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        VentaCarrito.add(jMenuItem4);

        VentanaCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/billete-de-banco.png"))); // NOI18N
        VentanaCompras.setText("Comprar vehiculos");
        VentanaCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaComprasActionPerformed(evt);
            }
        });
        VentaCarrito.add(VentanaCompras);

        jMenuBar1.add(VentaCarrito);

        VentanaEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/analisis-de-los-datos.png"))); // NOI18N
        VentanaEditar.setText("Editar datos");

        jMenuItem5.setText("Editar datos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        VentanaEditar.add(jMenuItem5);

        jMenuBar1.add(VentanaEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCerrarSesionActionPerformed
      System.exit(0);
    }//GEN-LAST:event_MenuCerrarSesionActionPerformed

    private void VentanaVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaVehiculosActionPerformed
        VehiculosForm v= new VehiculosForm();
        VentanaPrincipal.add(v);
       v.setVisible(true);
       
    }//GEN-LAST:event_VentanaVehiculosActionPerformed

    private void VentanaComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaComprasActionPerformed
       ComprarVehiculoForm cvf= new  ComprarVehiculoForm();
       VentanaPrincipal.add(cvf);
       cvf.setVisible(true);
    }//GEN-LAST:event_VentanaComprasActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        VerComprasForm cf= new VerComprasForm();
        VentanaPrincipal.add(cf);
        cf.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       EditarDatosForm ef= new EditarDatosForm();
       VentanaPrincipal.add(ef);
       ef.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCerrarSesion;
    private javax.swing.JMenu VentaCarrito;
    private javax.swing.JMenuItem VentanaCompras;
    private javax.swing.JMenu VentanaEditar;
    private javax.swing.JDesktopPane VentanaPrincipal;
    private javax.swing.JMenuItem VentanaVehiculos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
